#!/bin/bash
set -e

if [ $# -ne 1 ]; then
  echo "usage: $0 project"
  exit 1
fi

NAME=$1

mkdir -p $NAME/{cmd/api,internal/{handler,service,repository,model},pkg,config,migrations,scripts}
cd $NAME

# init go mod
go mod init $NAME

# generate main.go
cat > cmd/api/main.go <<EOF
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello $NAME")
}
EOF

# .gitignore
cat > .gitignore <<EOF
*.log
*.swp
.idea/
.vscode/
bin/
dist/
tmp/
EOF

# Makefile
cat > Makefile <<EOF
.PHONY: run build clean

run:
	go run ./cmd/api

build:
	go build -o bin/app ./cmd/api

clean:
	rm -rf bin tmp
EOF

# README
cat > README.md <<EOF
# $NAME
Go Project generated by go-project-gen.sh

## run
\`\`\`bash
make run
\`\`\`
EOF

echo "✅ $NAME project created successfully!"